apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-bluegreen
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
    strategy:
      blueGreen:
        # activeService specifies the service to update with the new template hash at time of promotion.
        # This field is mandatory for the blueGreen update strategy.
        activeService: rollouts-demo
        # previewService specifies the service to update with the new template hash before promotion.
        # This allows the preview stack to be reachable without serving production traffic.
        # This field is optional.
        previewService: rollouts-demo-preview
        # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
        # immediately before the promotion. If omitted, the default behavior is to promote the new
        # stack as soon as the ReplicaSet are completely ready/available.
        # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
        autoPromotionEnabled: false
  ---
  kind: Service
  apiVersion: v1
  metadata:
    name: rollouts-demo
    labels:
      app: rollouts-demo
  spec:
    selector:
      app: rollouts-demo
    ports:
    - port: 80
      targetPort: 8080
        ---
  kind: Service
    apiVersion: v1
    metadata:
      name: rollouts-demo
      labels:
        app: rollouts-demo
    spec:
      selector:
        app: rollouts-demo
      ports:
        - port: 80
          targetPort: 8080